version: 0.2

env:
  variables:
    TARGET_DIR: layerdist

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install wheel pipenv
  build:
    commands:
      - python setup.py bdist_wheel
      - pipenv --python 3.7
      - pipenv run python setup.py install
      - pipenv run pip freeze > requirements.txt
      - pipenv run pip install --find-links=dist -r requirements.txt -t $TARGET_DIR/python
  post_build:
    commands:
      - cd $TARGET_DIR
      - zip -r ../layer.zip python

artifacts:
  secondary-artifacts:
    LambdaLayerZipFile:
      files:
        - layer.zip
    CloudFormationTemplate:
      base-directory: cloudformation
      files:
        - lambdalayer.yaml


      
