AWSTemplateFormatVersion: 2010-09-09
Description: Lambda Layer containing lambdalogger Python module and its dependencies

Parameters: 
  LayerZipFileBucket:
    Description: S3 Bucket in which Lambda Layer ZIP file resides
    Type: String
  LayerZipFileKey:
    Description: S3 Key of Lambda Layer ZIP file
    Type: String

Resources: 
  LoggerLayer:
    Type: AWS::Lambda::LayerVersion
    Properties: 
      CompatibleRuntimes: 
        - python3.6
        - python3.7
      Content: 
        S3Bucket: !Ref LayerZipFileBucket
        S3Key: !Ref LayerZipFileKey
      Description: An opinionated logging framework for Lambda functions
      LayerName: LambdaLogger

Outputs:
  LayerArn:
    Description: Lambda Layer version ARN
    Value: !Ref LoggerLayer
    Export: 
      Name: !Sub "${AWS::StackName}-LayerArn"